window.dateRouletteIdeas = Object.freeze([
  "Sonnenuntergangsspaziergang",
  "Zusammen kochen und jeder wählt eine geheime Zutat",
  "Café-Date",
  "Filmabend mit Snacks",
  "Picknick mit unseren Lieblingssachen",
  "Eine neue Bäckerei testen",
  "Gemeinsam ein Lego- oder Puzzle-Projekt anfangen",
  "Frühstücks-Date statt Abend-Date",
  "Zusammen ein neues Dessert backen",
  "Minigolf oder etwas ähnliches",
  "Zuhause ein Blind-Tasting mit Snacks oder Getränken machen",
  "In eine andere Gegend fahren und dort spazieren gehen",
  "Eine TO-DO-Liste für die nächste Zeit zusammenstellen",
  "Zusammen ein neues Rezept kochen",
  "Eiscafé-Date mit Spaziergang danach",
  "Entspannungsdate mit Massage",
  "Morgens zusammen einen neuen Ort besuchen",
  "Arcade, Bowling oder etwas Wettbewerbmäßiges spielen",
  "Zusammen ein Abendessen mit Lieblingssnacks bauen",
  "Zusammen ein neues Brettspiel ausprobieren",
  "Zusammen einen Freizeitpark besuchen",
  "Zusammen Schlittschuhlaufen gehen",
]);