window.dateRouletteIdeas = Object.freeze([
  "Sonnenuntergangsspaziergang mit Lieblingsmusik",
  "Zusammen kochen und jeder wählt eine geheime Zutat",
  "Spontanes Café-Date mit nur einem Budget von 15 Euro",
  "Filmabend mit selbst gemachter Snackplatte",
  "Picknick auf einer Decke mit nur unseren Lieblingssachen",
  "Eine neue Bäckerei testen und danach durch die Gegend laufen",
  "Date im Auto mit Musik, Gesprächen und Nachtfahrt",
  "Gemeinsam ein Lego- oder Puzzle-Projekt anfangen",
  "Eine kleine Foto-Challenge draußen machen",
  "Frühstücks-Date statt Abend-Date planen",
  "Zusammen ein neues Dessert backen",
  "Jeder plant für den anderen eine 20-Minuten-Überraschung",
  "Minigolf oder etwas ähnlich Spielerisches ausprobieren",
  "Zuhause ein Blind-Tasting mit Snacks oder Getränken machen",
  "Ein gemeinsames Vision-Board oder Wunsch-Board basteln",
  "Spontan in eine andere Ecke der Stadt fahren und dort laufen",
  "Lieblingssongs gegenseitig vorstellen und bewerten",
  "Kuscheliger Serienabend mit Handy-freier Zeit",
  "Eine kleine Bucket-List nur für die nächsten vier Wochen schreiben",
  "Zusammen ein neues Rezept von Anfang bis Ende nachkochen",
  "Buchladen-Date und jeder sucht etwas für den anderen aus",
  "Eiscafé-Date mit langem Spaziergang danach",
  "Zu Hause ein kleines Spa-Date mit Maske und Ruheabend machen",
  "Morgens zusammen einen Ort besuchen, an dem wir noch nie waren",
  "Ein kleines Retro-Date mit alten Fotos und Erinnerungen machen",
  "Arcade, Bowling oder etwas mit freundlichem Wettbewerb spielen",
  "Zusammen ein Abendessen nur aus Lieblingssnacks bauen",
  "Sterne anschauen und eine neue Playlist dafür machen"
]);